### ISSUE TITLE
Issue with overlay-

### ISSUE THREAD

**Issue by Kalrin** [Bio2hazard/talis.xivplugin.twintania#6] opened 2014-01-01 23:49 UTC
I'm experiencing the same issues with the TT plugin as [outlined here](https://github.com/Icehunter/ffxivapp/issues/162). 

Clicking on the TT title bar causes all overlays (_including_ the parser widget that comes with XIV-APP) to disappear from the screen. 

Any chance you could update the code to be consistent with the parser widgets? 

Thanks~

**Comment by Bio2hazard** [comment] 2014-01-02 13:24
This should be fixed in the new version.

As I can't reproduce the issue, could you give the new version a try and let me know if your issue was resolved?

**Closed as completed** 2014-01-19 04:12 UTC
Labels: bug
